### PR TITLE
 ✅ ready for review: added, structured & cleaned docs

### PR DESCRIPTION
**Pull request by ElishaKay**
Updated GPTR Docs based on common questions on Discord & Github Issues.

Content edited includes:

- Getting started with Docker guides
- How to deploy on linux
- Running automated tests on Github & Locally
- How to setup with Ollama
- ...

- Restructured Docs Folder Structure to make it more intuitive for new users & updated the links to the docs within the repo for any links that may have changed.

image

Screen Shot 2024-08-27 at 23 26 28

image

image

### CODE REVIEW

**Comment by assafelovic** [comment]
This is awesome @ElishaKay lmk when ready to review

**Comment by assafelovic** [comment]
Also check out the conflicts based on latest master commits

**Comment by ElishaKay** [comment]
> Also check out the conflicts based on latest master commits

fixed

**Comment by ElishaKay** [comment]
> This is awesome @ElishaKay lmk when ready to review

@assafelovic  ✅ ready for review

**Review by assafelovic — APPROVED** [review]

**Pull request merged**
