### PR TITLE
Feature/Virtual Environment and Poetry

### PR DESCRIPTION
**Pull request by aaaastark**
I've implemented the configurations for both Virtual Environment and Poetry. Additionally, I've successfully addressed two issues: one related to `duckduckgo_search==4.1.1` and the other involving the `OSError` related to the inability to load the library 'gobject-2.0-0'. 

@datafyresearcher, this account belongs to me.

### CODE REVIEW

**Comment by aaaastark** [comment]
Kindly review `Feature/Virtual Environment and Poetry` and then merge it with `master` branch. @assafelovic

**Comment by madvid** [comment]
+1

**Review by assafelovic — APPROVED** [review]
This is a great addition thank you!

**Comment by assafelovic** [comment]
Sorry for late response on this this is a great addition thank you @aaaastark

**Comment by Undertone0809** [comment]
image


~ is better.

**Pull request merged**
