### PR TITLE
use langchain

### PR DESCRIPTION
**Pull request by hwchase17**
This uses langchain, values being:

1 - automatically works with langsmith out of the box

Screenshot 2023-07-28 at 12 16 57 PM

2 - sets it up to easily (relatively easily) start using other language models (need to discuss how exactly that should be configured)

### CODE REVIEW

**Comment by hwchase17** [comment]
this needs to wait for the next version of langchain actually

**Review by gregdrizz — APPROVED** [review]

**Review by gregdrizz — CHANGES_REQUESTED** [review]
@hwchase17 Thanks! 
We'll wait for the update and then merge :)

**Review by gregdrizz — APPROVED** [review]
Works with the new version of langchain(0.0.247)

**Comment by hwchase17** [comment]
@gregdrizz yup - this should be good to go in whenever!

**Pull request closed without merging**
