### PR TITLE
【Added】Enable support for processing online documents in hybrid mode

### PR DESCRIPTION
**Pull request by MC-shark**
The hybrid mode currently can only configure document files through the configuration file ./my-docs, which is not very flexible.
Now, it is possible to pass them using the document_urls parameter.

### CODE REVIEW

**Comment by assafelovic** [comment]
@MC-shark FYI there is a conflict with latest merge. Also, would you mind sharing an example of how to use it here: https://github.com/assafelovic/gpt-researcher/blob/master/docs/docs/examples/hybrid_research.md

**Comment by MC-shark** [comment]
> @MC-shark仅供参考，最新合并存在冲突。另外，您介意在这里分享一个如何使用它的示例吗：https://github.com/assafelovic/gpt-researcher/blob/master/docs/docs/examples/hybrid_research.md

OK

**Comment by MC-shark** [comment]
I added an example of online documents in hybrid mode #1046

**Review by assafelovic — APPROVED** [review]

**Comment by assafelovic** [comment]
Thank you @MC-shark this is an amazing addition!

**Pull request merged**
