### PR TITLE
Enhance File Upload Component with Improved UI and Delete Functionality

### PR DESCRIPTION
**Pull request by muhammedsaidckr**
This pull request introduces several enhancements to the FileUpload component. Below are the detailed changes:

Uploaded Files List:
-     Styled the list of uploaded files for a cleaner, more organized presentation.
-     Used Tailwind CSS classes to ensure consistent design and spacing across the component.

'n' to &apos;n&apos; because typescript error 

Added preventDefault in the delete button onClick event to prevent the modal from closing.

Screenshot from 2024-07-25 17-19-25

### CODE REVIEW

**Comment by muhammedsaidckr** [comment]
@ElishaKay 
Yeah you are right that would be better uploaded_files_count == 0? then Uploaded files will be hidden. I will apply that. 

The app seems to get stuck on the words: "✍️ Writing summary for research task:..."  

I experienced the same situation, but It responds even though it is late. I think there is a problem on the "openai" side right now. https://status.openai.com/

**Comment by ElishaKay** [comment]
> @ElishaKay Yeah you are right that would be better uploaded_files_count == 0? then Uploaded files will be hidden. I will apply that.
> 
> The app seems to get stuck on the words: "✍️ Writing summary for research task:..."
> 
> I experienced the same situation, but It responds even though it is late. I think there is a problem on the "openai" side right now. https://status.openai.com/

You may be on to something there - same error on master

**Comment by ElishaKay** [comment]
@FarVision2 made a good point here about [filtering by domain name here ](https://github.com/assafelovic/gpt-researcher/pull/700#issuecomment-2246245830)

How about: if the Selected Retriever supports filtering Search Results by domain, that option will be available via the UX as well?

For example, if the retriever=google, appending filters to the query should work:
`site:lifewire.com OR site:nasa.gov electric vehicles`

**Comment by muhammedsaidckr** [comment]
Screenshot from 2024-07-26 16-31-59

Necessary changes have been applied to uploaded files @ElishaKay

**Comment by muhammedsaidckr** [comment]
> @FarVision2 made a good point here about [filtering by domain name](https://github.com/assafelovic/gpt-researcher/pull/700#issuecomment-2246245830)
> 
> How about: if the Selected Retriever supports filtering Search Results by domain, that option will be available via the UX as well?
> 
> For example, if the retriever=google, appending filters to the query should work: `site:lifewire.com OR site:nasa.gov electric vehicles`

I'll look into this and see what we can do.

**Comment by ElishaKay** [comment]
all tests pass

**Review by ElishaKay — APPROVED** [review]

**Pull request merged**
