### PR TITLE
Optimize FileUpload Component

### PR DESCRIPTION
**Pull request by muhammedsaidckr**
This pull request addresses several issues and implements optimizations in the FileUpload component. The changes include resolving React Hook warnings, improving performance, and ensuring proper dependency management.

### 1. Optimize fetchFiles function with useCallback
- Wrapped the `fetchFiles` function in a `useCallback` Hook.
- Added `host` to the dependency array of `useCallback`.
- Updated the `useEffect` dependency array to include `fetchFiles`.

### 2. Add unique key prop to iterator element
- Created a `uniqueKey` variable using the index to ensure unique keys for each iterated element.
- Added the `key` prop to the div element in the iterator.

### FileUpload Component Optimization
```jsx
// Before
import React, { useEffect, useState } from 'react';

const FileUpload = () => {
  const [files, setFiles] = useState([]);
  const host = getHost();
  
  const fetchFiles = async () => {
    try {
      const response = await axios.get(`${host}/files/`);
      setFiles(response.data.files);
    } catch (error) {
      console.error('Error fetching files:', error);
    }
  };

  useEffect(() => {
    fetchFiles();
  }, []);

// After
import React, { useCallback, useEffect, useState } from "react";

const FileUpload = () => {
  const [files, setFiles] = useState([]);
  const host = getHost();

  const fetchFiles = useCallback(async () => {
    try {
      const response = await axios.get(`${host}/files/`);
      setFiles(response.data.files);
    } catch (error) {
      console.error('Error fetching files:', error);
    }
  }, [host]);

  useEffect(() => {
    fetchFiles();
  }, [fetchFiles]);
```

### Iterator Key Addition
```jsx
// Before
return (
  <div></div>
);

// After
const uniqueKey = `langgraphButton-${index}`;
return (
  <div key={uniqueKey}></div>
);
```

## Why These Changes Are Necessary
1. Resolves the React Hook exhaustive-deps warning.
2. Improves performance by preventing unnecessary recreation of the `fetchFiles` function.
3. Ensures that the `useEffect` Hook properly depends on `fetchFiles`, allowing it to re-run if `host` changes.
4. Resolves the React/ESLint warning about missing keys in iterators.
5. Improves rendering performance for lists.

## Potential Impacts
- Improved component performance.
- More predictable behavior when `host` changes.
- Better React reconciliation for iterated elements.

## Testing Done
- Verified that all React Hook warnings are resolved.
- Ensured that file fetching functionality remains unchanged.
- Tested with different `host` values to ensure proper reactivity.
- Verified that iterated elements render correctly with unique keys.

## Next Steps
- Review and merge if approved.
- Consider applying similar optimizations to other components if needed.
- Update any documentation or comments to reflect these changes.

Please review and let me know if any further changes, testing, or clarifications are required.

### CODE REVIEW

**Comment by ElishaKay** [comment]
Sup @muhammedsaidckr 

I'm looking forwarding to digging into this next week.

U da man!

**Comment by muhammedsaidckr** [comment]
> Sup @muhammedsaidckr
> 
> I'm looking forwarding to digging into this next week.
> 
> U the man!

What about you @ElishaKay 

I am also woking on the build errors. For example creating the types and interfaces for some parameters etc. I can share that changes. 

Thanks!

**Comment by assafelovic** [comment]
Thanks @muhammedsaidckr ! This is super valuable. Looking forward to seeing the final PR for this. @ElishaKay lead this to production 🥇

**Comment by ElishaKay** [comment]
Interesting concept @muhammedsaidckr 

You're moving in the right direction here regarding cleaning up the errors in the dev console.

a) Seeing 3 more here:

Screen Shot 2024-09-10 at 10 40 56

b) How about the logo? Any ideas why we don't see the GPTR logo there? 

Originally I thought it was a caching issue, but I also don't see the right logo in localhost:

Maybe it needs to be converted into svg?

https://github.com/assafelovic/gpt-researcher/blob/master/frontend/static/gptr-logo.png

**Comment by assafelovic** [comment]
@ElishaKay @muhammedsaidckr what's the update on this PR?

**Comment by ElishaKay** [comment]
Up to @muhammedsaidckr if he wants to abstract away the GPTR host url in this PR or whether we should handle it in another

**Comment by muhammedsaidckr** [comment]
> Up to @muhammedsaidckr if he wants to abstract away the GPTR host url in this PR or whether we should handle it in another

@ElishaKay @assafelovic Let's change the other requests and build errors in another pr because it will continue for a while

**Review by ElishaKay — COMMENTED** [review]
approved

**Review by ElishaKay — APPROVED** [review]
approved

**Pull request merged**
