### PR TITLE
Hotfix: Update base.py

### PR DESCRIPTION
**Pull request by kesamet**
To fix the bug indicated in https://github.com/assafelovic/gpt-researcher/issues/901 and https://github.com/assafelovic/gpt-researcher/issues/900

### CODE REVIEW

**Comment by kesamet** [comment]
@assafelovic urgent fix

**Review by assafelovic — APPROVED** [review]
Thank you great call!

**Comment by assafelovic** [comment]
Good catch @kesamet

**Comment by PieBru** [comment]
I confirm it works.
Thank you much.
Piero

**Pull request merged**
