### PR TITLE
Added Config UI

### PR DESCRIPTION
**Pull request by Ethan-Otto**
Added UI for controlling the config. I made the config.json in the root folder the default config, and the UI can update it directly. Allows much faster testing of different parameters especially when using docker.
Also added descriptions of each variable

image

### CODE REVIEW

**Comment by assafelovic** [comment]
@Ethan-Otto this is great! Can you please refine and include on the following params:

Report format, total words, search engine, llm provider and max iterations? The idea is to expose only the report related params. Thanks!

**Comment by Ethan-Otto** [comment]
@assafelovic So hide everything else?

**Comment by Ethan-Otto** [comment]
@assafelovic so hide everything else?

**Comment by assafelovic** [comment]
Not to hide but remove, I think some of these config params should be hidden and not modified since it may confuse or break the UX/UI. Lmk if you can, if not I can do it later in the week

**Review by notvicent3 — COMMENTED** [review]
Didn't check it running atm, but as I can see in the code seems pretty nice.

**Comment by Ethan-Otto** [comment]
@assafelovic Added a filter to control what's displayed/updated
image

**Comment by assafelovic** [comment]
Unfortunately this PR is stale and consists of too many conflicts. Also we've shifted focus to a new NextJS app. Closing this.

**Pull request closed without merging**
