### PR TITLE
Db support

### PR DESCRIPTION
**Pull request by ElishaKay**
Optionally save logs & reports in MongoDB

### CODE REVIEW

**Comment by ElishaKay** [comment]
Added the 2 relevant services to consume the logs & save them in mongo.
Adding now the relevant changes to the gpt-researcher python service

**Comment by ElishaKay** [comment]
All required files added.
Tested on Mac & all tests pass
Ready for review

**Review by notvicent3 — COMMENTED** [review]
Thats awesome!

**Review by assafelovic — APPROVED** [review]

**Comment by ElishaKay** [comment]
Closing for now since there's a chance that commits were squashed on this branch.

We might be able to leverage the JavaScript code in this branch on the upcoming NextJS server, but should probably:
- remove the Kafka middleman
- save in postgres instead of mongodb
- leverage the `stream_output` function

Requires design review if we'd like to implement [Langchain Retrievers which leverage a PGVector ](https://python.langchain.com/v0.2/docs/integrations/retrievers/self_query/pgvector_self_query/) as [proposed by this user in the discord](https://discord.com/channels/1127851779011391548/1131684365303296041/1246789423496953856).

**Pull request closed without merging**
