### PR TITLE
Support for detailed report generation!

### PR DESCRIPTION
**Pull request by proy9714**
More updates to come...

### CODE REVIEW

**Comment by proy9714** [comment]
There you go @assafelovic . Hope this provides a great starting for the community to contribute!

**Comment by assafelovic** [comment]
Thanks @proy9714 you rock! I’ll take an in depth look soon. Did you check out the STORM methodology?

**Comment by proy9714** [comment]
Yes, I am aware of the STORM methodology. But I would argue that since the final LLM call needs to be made after subsections are written it again limits the length of the output report.

In my case I have followed a similar approach but the reports for the subsections are simply appended together instead of making a final LLM call again. Have opted for manual methods instead of langgraph for the time being. (May be updated in the future)

In this method it follows a similar approach to the STORM methodology

1. Inital research

2. From that subtopics are constructed 

3. For each subtopic the headers of the subtopic report are extracted and accumulated

4. For each subtopic a report is generated making sure that any information about the headers accumulated until now are not re-generated.

5. An additional introduction section is written along with a table of contents constructed from the entire report.

6. The final report is constructed by appending these : Intro + Table of contents + Subsection reports



An advantage of this method is that on increasing the number of subtopics the report length increases and becomes more detailed. Of course, further changes and refinements can be made to smooth out the process further. 

Help from the community is appreciated 😄

**Comment by proy9714** [comment]
[46977befabad4c64b1d265a5e376c5fe.pdf](https://github.com/assafelovic/gpt-researcher/files/14801328/46977befabad4c64b1d265a5e376c5fe.pdf)

**Comment by proy9714** [comment]
Here you go. A sample detailed report I ran on "OpenAI".

[OpenAI.pdf](https://github.com/assafelovic/gpt-researcher/files/14801962/OpenAI.pdf)

**Comment by SomethingGoodLLC** [comment]
@proy9714 that reports awesome! That’s one of the things I wanted with GOTResearcher: longer reports. I played around with the JSON settings, making the max tokens 120k (in line with GPT4) to no avail 

I’d be excited with Gemini’s one million+ context window too. 

How did you get your report, so long?

on the flip side, the current reports are still the best default. I’ve used it personally for many business ideas, and am impressed by the quality of sources cited and how recently they were published

**Comment by proy9714** [comment]
> @proy9714 that reports awesome! That’s one of the things I wanted with GPTResearcher: longer reports. I played around with the JSON settings, making the max tokens 120k (in line with GPT4) to no avail 
> 
> I’d be excited with Gemini’s one million+ context window too. 
> 
> How did you get your report, so long?
> 
> on the flip side, the current reports are still the best default. I’ve used it personally for many business ideas, and am impressed by the quality of sources cited and how recently they were published. It’s easy to quickly read 

The more the number of subtopics the more the length of the report 😄

**Comment by SomethingGoodLLC** [comment]
Would it be possible to send all of the subsections back again to the LLM and be like expand upon this? Then use that to double the report?

**Comment by proy9714** [comment]
> Would it be possible to send all of the subsections back again to the LLM and be like expand upon this? Then use that to double the report?

Yes sure....if time and cost are not an issue than of course that is possible!

**Comment by therealtimex** [comment]
> Here you go. A sample detailed report I ran on "OpenAI". @assafelovic
> 
> [OpenAI.pdf](https://github.com/assafelovic/gpt-researcher/files/14801962/OpenAI.pdf)

I love the report. If you can add citation in the text, it's really complete.

**Comment by assafelovic** [comment]
@proy9714 I second @therealtimex for citation!

**Comment by proy9714** [comment]
@assafelovic @therealtimex  There you go!

**Comment by therealtimex** [comment]
> @assafelovic @therealtimex There you go!

That's so fast. Would you be able to gen a new report with the inline citations?

**Comment by proy9714** [comment]
> > @assafelovic @therealtimex There you go!
> 
> That's so fast. Would you be able to gen a new report with the inline citations?

[GPT Researcher.pdf](https://github.com/assafelovic/gpt-researcher/files/14811006/GPT.Researcher.pdf)

**Comment by therealtimex** [comment]
> > > @assafelovic @therealtimex There you go!
> > 
> > 
> > That's so fast. Would you be able to gen a new report with the inline citations?
> 
> [GPT Researcher.pdf](https://github.com/assafelovic/gpt-researcher/files/14811006/GPT.Researcher.pdf)

Love it.

**Comment by assafelovic** [comment]
@proy9714 you’re truly a star 👏
One thing to see when diving deeper into the report is that it loses context from the original. It started with describing gpt researcher but then 80% of the report was about GPT. I assume this might be related to the sources and search query results, and for other topics would be better. I’m wondering if it’s worth seeing how to better generate subtopics based on returned results such as with STORM approach 🤔

**Comment by proy9714** [comment]
> @proy9714 you’re truly a star 👏 One thing to see when diving deeper into the report is that it loses context from the original. It started with describing gpt researcher but then 80% of the report was about GPT. I assume this might be related to the sources and search query results, and for other topics would be better. I’m wondering if it’s worth seeing how to better generate subtopics based on returned results such as with STORM approach 🤔

Yeah that's a great observation! I guess tweaking the subtopics generation and prompts would be the way to go. But yeah its subject to a lot of experimentation. I guess the STORM method for generating subtopics could help along with modified prompts. Would be nice if the community could experiment as well!

**Comment by assafelovic** [comment]
@proy9714 For sure this is the start of a completely new innovation and I will publish and promote this as soon as we merge. Also happy to get your details or ping me on discord!

I think one last thing to complete this is
1. Do a search before generating the topics and then generating topics based on the search results
2. Consider putting a max for subtopics since I assume the greater the topics the more chance for hallucinations or irrelevant information.

wdyt?

**Comment by proy9714** [comment]
> @proy9714 For sure this is the start of a completely new innovation and I will publish and promote this as soon as we merge. Also happy to get your details or ping me on discord!
> 
> I think one last thing to complete this is
> 
> 1. Do a search before generating the topics and then generating topics based on the search results
> 2. Consider putting a max for subtopics since I assume the greater the topics the more chance for hallucinations or irrelevant information.
> 
> wdyt?

I think both of those are actually done already! 

1. If you look at the code there is an initial research being done on the given main topic before generating the subtopics with that search information.

2. Also there is a new config variable for max_subtopics which is being passed to the LLM during subtopic generation!

**Comment by assafelovic** [comment]
@proy9714 testing it right now, I'll modify a bit and merge! For example I'd like the "detailed report" to actually be an option in addition to research report, probably a check mark for "detailed report" - true or false. Also seeing some UX to modify since there is a wait time of generation between the initial generation and the subtopics on the UI. Overall this is amazing!

**Comment by assafelovic** [comment]
@proy9714 also lmk from your end if there's anything in addition that you'd like to add before I do a final run

**Comment by assafelovic** [comment]
@proy9714 I see that the first half of report is perfect (detailed content + sources) however the second half usually is shorter and without sources. Any quick idea why?

**Comment by proy9714** [comment]
Can you show me a report....I don't understand - what you mean by the second half @assafelovic

**Comment by assafelovic** [comment]
@proy9714 I found the issue. for some subtopics there is not relevant information found from the ContextRetriever embedding. I reduced the threshold for similarity score and it's returning better results now. Also modified some prompts (pull latest).

**Comment by proy9714** [comment]
> @proy9714 I found the issue. for some subtopics there is not relevant information found from the ContextRetriever embedding. I reduced the threshold for similarity score and it's returning better results now. Also modified some prompts (pull latest). 

Can I also suggest one other change....in the fallback from tavily can you use Newspaper3k instead Duckduckgo search. This is because sometimes (quite often) I have run into a rate limiting with Ddgs. newspaper3k library does not seem to have this problem.

**Comment by proy9714** [comment]
Also....if as you said for some subtopic we don't get any relevant data from our research, won't it be better to skip that subtopic altogether and return ""??

**Comment by therealtimex** [comment]
> Also....if as you said for some subtopic we don't get any relevant data from our research, won't it be better to skip that subtopic altogether and return "" ?

I believe that returning an empty string is not as preferable as returning poor content because users are more likely to perceive it as an error. Poor content resulting from a lack of relevant data is evident in the citations.

**Comment by assafelovic** [comment]
@proy9714 any additions you'd like to add before I merge this? This is huge for the community!

**Comment by proy9714** [comment]
> @proy9714 any additions you'd like to add before I merge this? This is huge for the community!

No nothing right now I guess.... I'll connect with you on discord

**Review by assafelovic — APPROVED** [review]

**Comment by therealtimex** [comment]
Following up on this great pr, I think it would be great if we can feed the agent with our own documents. Is it currently possible?

**Pull request merged**
