### PR TITLE
Support langchain vectorstores

### PR DESCRIPTION
**Pull request by hslee16**
## Goal

This PR aims to add support for [Langchain Vectore Stores](https://python.langchain.com/v0.2/docs/concepts/#vector-stores)
For a list of vector stores currently supported by Langchain, please refer to [here](https://python.langchain.com/v0.2/docs/integrations/vectorstores/)

## Details
1. gpt-researcher currently generates embeddings via openai whenever we call it with scraped data from the web or local files.
2. For those that already use langchain with a corresponding vector store, this step is redundant as embeddings will have been generated (and stored)
3. We can use the vector store as the document store instead of re-generating embeddings every time we perform research.

## TODO

- [x] create unit test
- [x] add example to documentation using [FAISS memory vector store](https://python.langchain.com/v0.2/docs/integrations/vectorstores/faiss/)

### CODE REVIEW

**Comment by hslee16** [comment]
Would appreciate some early reviews, comments, & questions.

**Comment by ElishaKay** [comment]
Hey @hslee16 

What a pleasant surprise!

Looks like an awesome contribution for the community! The vector store section of the backend is definitely a black box for me currently, so I'd love to see what's getting persisted on the backend across runs.

Initial questions:
- how are you running the FAIS service? (It doesnt seem like [the docker image](https://hub.docker.com/r/daangn/faiss) is very popular or has simple docs)
- have you considered the PGVector store or do you perhaps have an example of how the Vector store is selected & leveraged?

Looking forward 🙏

**Comment by hslee16** [comment]
Unit test and documentation has been added.

@ElishaKay @assafelovic ready for review.

**Comment by ElishaKay** [comment]
@hslee16, holy shnikes!
That's awesome 

Cant wait to play with it over the weekend

@assafelovic, I'll pass you a Postgres connection string for the tests 

Ideas for further down the roadmap: 
 - when a user uploads documents, docs are embedded & added to the vectorstore
 - scraped webpages are inserted into the vectorstore
 - user queries & other user input can be stored in the vector store for personalization 

Brilliant 👏

**Comment by hslee16** [comment]
@ElishaKay while your ideas are great, they are unfortunately outside the scope of this PR.
I'll visit them once this one is merged.

**Comment by ElishaKay** [comment]
@hslee16 agreed - let's keep the PR light.

P.S. for the `faiss-cpu`, we can move it directly into the docker-tests by editing docker-compose.yml of the the gpt-researcher-tests container to:

`pip install pytest pytest-asyncio faiss-cpu &&`

In that way, `faiss-cpu` will only be installed for tests - we're trying to keep the master requirements.txt as lean as possible.

**Comment by hslee16** [comment]
@ElishaKay done

**Review by assafelovic — APPROVED** [review]
This is brilliant and love the documentation piece

**Pull request merged**
