### PR TITLE
[Experimental] Chat with history

### PR DESCRIPTION
**Pull request by khoangothe**
I am trying to implement chat history to chat with the final report. The code is just experimental since I'm not sure whether this is where I should put the chat agent. The code will put the report and vectorize in a inmemory vectorstore to get the relevant chunks and I used default LangGraph React Agent. Would be cool if I could have some feedbacks on how to proceed! Thanks guys

Here's the UI (default to chatting after having a report, pressing the search symbol will conduct another research)
image

### CODE REVIEW

**Comment by ElishaKay** [comment]
Pretty awesome @khoangothe!

@assafelovic, deployed a demo of the branch here: https://gptr-green.gptbud.com/

@khoangothe 

a) You'll want to think about the text in the homepage, as defined in "frontend/nextjs/components/InputArea.tsx".

Perhaps conditional text based on the current state?

Screen Shot 2024-09-10 at 9 34 16

b) I've played with the branch a bit & the results are pretty solid for the follow up questions

I'm curious we should leverage the new GPTR vector_store parameter:

```
researcher = GPTResearcher(
            query=query,
            report_type="research_report",
            report_source="langchain_vectorstore",
            vector_store=vector_store,
        )
```

**Comment by khoangothe** [comment]
@ElishaKay Got it thanks for the feedback! I'll see if I can push a change soon. Hoping can change the answer to some chat-like interface too.

Regarding the Vector Store, I saw your ideas in the VectorStore PR #781 and I think it would be very cool to have those implemented as well. I think we can store all of the related contents into a vectorstore and retrieve the information when ask for more context. But I struggle in how best to store new data since the vectorstore is inputted by the user which makes it a bit complicated 

Case 1: Since we are storing every crawled info/documents in "vector_store", ideally the "vector_store" should be empty or contain related information so the new page won't contaminate the existing data and provide better queries. 
Case 2: We just want to store all the results, so user can have an all knowing bot that can answers related to his/her previous reports. 

Not sure which case the user will want, but I think I can quickly change the InMemoryVectorStore in the code to the inputted VectorStore after we got this features! Would be cool if we can have a discussion or you could help with some ideas about this! 

> Pretty awesome @khoangothe!
> 
> a) You'll want to think about the text in the homepage, as defined in "frontend/nextjs/components/InputArea.tsx".
> 
> Perhaps conditional text based on the current state?
> 
> Screen Shot 2024-09-10 at 9 34 16
> 
> b) I've played with the branch a bit & the results are pretty solid for the follow up questions
> 
> I'm curious whether we should leverage the new [GPTR vector_store parameter](https://docs.gptr.dev/docs/gpt-researcher/vector-stores):
> 
> ```
> researcher = GPTResearcher(
>             query=query,
>             report_type="research_report",
>             report_source="langchain_vectorstore",
>             vector_store=vector_store,
>         )
> ```

**Comment by ElishaKay** [comment]
Good points @khoangothe 

Case 1: Agreed. If we add a chat_id or task_id to the vectorstore records, I guess we'd be able to filter vectorstore searches by chat_id

Case 2: personalization would be great - but it depends on whether we want to have user authentication & multi-user logic within this repo, or whether the GPTR community should build that out independently on a case by case basis - not yet decided

Case 3: Faiss seems like a good candidate since it seems to come out of the box with a pip package. Postgres could be good as well for SQL querying. Have a look here at the Langchain Vector Stores: 

https://python.langchain.com/v0.2/docs/integrations/vectorstores/

**Comment by khoangothe** [comment]
@ElishaKay  Thanks man, I just added a PR for VectorStore #838 . I think if we want to proceed with the vector_store ideas, we need to implement this first. Then we can continue with this branch to chat with the crawled information in the vector db

**Comment by ElishaKay** [comment]
@khoangothe 

Good thinking!
I've merged #838 into the AI Dev Team flow in #819 
I'd like to also merge this PR into the same AI Dev Team branch & do extensive testing.

**Comment by khoangothe** [comment]
> you can feel free to push up commits to the AI Dev Team branch if inspiration sparks

Thanks man, I do have some ideas on how to leverage the vector store. I'll read through the AI Dev Team branch and see what I can add

**Comment by assafelovic** [comment]
Hey @khoangothe any update on this? Would love see this merged!

**Comment by khoangothe** [comment]
Thank @assafelovic , my plan was to have the vector_store pr merge first and then utilize the vector_store for this pr. With that functionality, I can store crawled data  into an in memory_db, then we can chat with the data in DB (not just the report).
If you prefer, I can also merge the vector_store to this pr and then push a commit altogether to chat with the crawled data. I'm working on it right now and can push a commit in either case soon!

**Comment by assafelovic** [comment]
Got it @khoangothe apologize in advance that we've refactored quite a lot of the codebase to be better written so it created some conflicts with the recent PRs

**Comment by khoangothe** [comment]
@assafelovic  no worries! I think I'll just close this PR and make another one instead of resolving the merge conflict so it's easier to keep track of the change history.

**Pull request closed without merging**
