### PR TITLE
add support for custom openai api embeddings 

### PR DESCRIPTION
**Pull request by sebaxzero**
example of .env for lm studio:

```
OPENAI_BASE_URL="http://localhost:1234/v1"
OPENAI_API_KEY="local"
EMB_MODEL="local"
```

key does not matter but is required to load, model does not matter and is not required.

i just tested researching with mistral v2 7b q8 and nomic embed text f16 and it worked better than expected

### CODE REVIEW

**Comment by assafelovic** [comment]
Hey @sebaxzero this is amazing thank you very much for the effort. I've added a new documentation page specifically for this here: https://github.com/assafelovic/gpt-researcher/blob/master/docs/docs/gpt-researcher/llms.md
Please merge it to this branch and feel free to update it with all information to make it run. Thank you!

**Comment by assafelovic** [comment]
also @sebaxzero in your PR you removed the default embeddings. Would you mind adding another param for `custom` and to support custom endpoints?

**Comment by gschmutz** [comment]
@sebaxzero and @assafelovic  wouldn't it be clearer to name the environment variable `OPENAI_EMBEDDING_MODEL` to be consistent with `AZURE_EMBEDDING_MODEL` and `OLLAMA_EMBEDDING_MODEL` I have used for Ollama.

**Comment by sebaxzero** [comment]
I have added the custom case to `EMBEDDING_PROVIDER` and set the environment variable for model name to `OPENAI_EMBEDDING_MODEL`. Default values have been configured for lmstudio.

#### Example of .env file:
```env
EMBEDDING_PROVIDER="custom"
OPENAI_BASE_URL="http://localhost:1234/v1"
OPENAI_API_KEY="custom"
OPENAI_EMBEDDING_MODEL="custom"
```

**Comment by assafelovic** [comment]
Thank you @sebaxzero !! Can you confirm you've tested it and that I can merge?

**Comment by sebaxzero** [comment]
@assafelovic yes

**Review by assafelovic — APPROVED** [review]

**Pull request merged**
