### PR TITLE
Reports from documents!

### PR DESCRIPTION
**Pull request by proy9714**
# A highly requested feature!!! 🔥 🚀 💯 

## Now generate reports from your own documents!!

Just add the env variable DOC_PATH pointing to the folder where your document are located and choose MY DOCUMENTS from the source.

image

Support for a few basic document types, the community integrate many more from the host of document loaders provided by the langchain ecosystem.

There you go @assafelovic !

### CODE REVIEW

**Comment by assafelovic** [comment]
This is huge @proy9714 will review it in a few days, feel free to continue refining in the meanwhile 👏🤩

**Comment by ElishaKay** [comment]
Looks good guys!
I noticed that there is an error running on mac:

`docker-compose up --build` 

[The fix is here.](https://github.com/assafelovic/gpt-researcher/pull/452/commits/7af0de206327bc91070da76813e94e0acb1347fe)

The error is:

 Failed to fetch http://deb.debian.org/debian-security/pool/updates/main/f/firefox-esr/firefox-esr_115.3.1esr-1%7edeb11u1_arm64.deb  404  Not Found [IP: 199.232.82.132 80]
#0 2.622 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by ElishaKay** [comment]
Within the Readme, you'll want to be a little more specific on the limits of the `DOC_PATH` variable - ideally it should be somewhere within the `gpt-researcher` project folder.

For example, we should recommend something like:

`DOC_PATH=./docs/my-docs`

Reason being, when you're running the app via Docker, you'll get a "Permission Denied" error when you try to set the DOC_PATH variable to your Downloads folder, for example. Plus some other errors and complexity which arise, like needing to load volumes into Docker, which we should avoid.

**Comment by proy9714** [comment]
Hey @assafelovic I was on vacation and back now. Is there any problems with merging this? Can you quickly get me up to speed?!

**Comment by assafelovic** [comment]
@proy9714 welcome back from vacation :)

@ElishaKay took the liberty of fixing some issues with docker and created a new PR for this. Ping me on Discord and I'll be happy to jump you in!

**Pull request closed without merging**
