### PR TITLE
chore: Update retrievers imports

### PR DESCRIPTION
**Pull request by 0x11c11e**
Description:

The imports for the retrievers module have been updated to include the new `ExaSearch` class. This enhancement adds a new retriever capability using the **Exa API**, enabling more robust and flexible search functionalities.

Key Changes:

- Added `ExaSearch` class to the retrievers module.
- Updated import statements to integrate `ExaSearch`.
- Provided necessary documentation for `ExaSearch` usage.

Please review the changes and let me know if any adjustments are needed.

### CODE REVIEW

**Review by assafelovic — APPROVED** [review]
This is great!

**Comment by assafelovic** [comment]
Thanks @0x11c11e also love the general refactoring making the actions file more readable. Keep it up!

**Comment by ElishaKay** [comment]
Nice to e-meet you @0x11c11e & glad to have you on board :)

There's an edge case here that we need to take into consideration.
When running the multi_agents feature via the CLI, the process crashes.

Attaching the error log below & the [temporary fix](https://github.com/assafelovic/gpt-researcher/pull/523/commits/b1fa7ebfff2c78600e2db04e1f4d2d11d1c1c359) so that the langgraph multi_agents flow can run to completion via the CLI.

```
(my_env) root@gptr-green:~/gpt-researcher/multi_agents# python main.py
USER_AGENT environment variable not set, consider setting it to identify your requests.
MASTER: Starting the research process for query 'Is AI in a hype cycle?'...
RESEARCHER: Running initial research on the following query: Is AI in a hype cycle?
Traceback (most recent call last):
  File "/root/gpt-researcher/multi_agents/main.py", line 62, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/gpt-researcher/multi_agents/main.py", line 57, in main
    research_report = await chief_editor.run_research_task()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/gpt-researcher/multi_agents/agents/master.py", line 64, in run_research_task
    result = await chain.ainvoke({"task": self.task})
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/environments/my_env/lib/python3.12/site-packages/langgraph/pregel/__init__.py", line 1504, in ainvoke
    async for chunk in self.astream(
  File "/root/environments/my_env/lib/python3.12/site-packages/langgraph/pregel/__init__.py", line 1333, in astream
    _panic_or_proceed(done, inflight, step)
  File "/root/environments/my_env/lib/python3.12/site-packages/langgraph/pregel/__init__.py", line 1537, in _panic_or_proceed
    raise exc
  File "/root/environments/my_env/lib/python3.12/site-packages/langgraph/pregel/retry.py", line 120, in arun_with_retry
    await task.proc.ainvoke(task.input, task.config)
  File "/root/environments/my_env/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 2540, in ainvoke
    input = await step.ainvoke(input, config, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/environments/my_env/lib/python3.12/site-packages/langgraph/utils.py", line 117, in ainvoke
    ret = await asyncio.create_task(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/gpt-researcher/multi_agents/agents/researcher.py", line 43, in run_initial_research
    return {"task": task, "initial_research": await self.research(query=query, verbose=task.get("verbose"),
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/gpt-researcher/multi_agents/agents/researcher.py", line 16, in research
    researcher = GPTResearcher(query=query, report_type=research_report, parent_query=parent_query,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/gpt-researcher/gpt_researcher/master/agent.py", line 62, in __init__
    self.retriever = get_retriever(self.headers.get("retriever")) or get_retriever(self.cfg.retriever)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/gpt-researcher/gpt_researcher/master/actions.py", line 67, in get_retriever
    from gpt_researcher.retrievers import TavilySearch
  File "/root/gpt-researcher/gpt_researcher/retrievers/__init__.py", line 5, in <module>
    from .exa.exa import ExaSearch
  File "/root/gpt-researcher/gpt_researcher/retrievers/exa/exa.py", line 3, in <module>
    from exa_py import Exa
ModuleNotFoundError: No module named 'exa_py'
```

**Comment by 0x11c11e** [comment]
It appears that the `exa_py` module is missing. You need to install it using:

`pip install exa_py`

However, I am not encountering this error. If that didn't work then could you try cloning the source code again in a fresh environment and install all the requirements? One of these approaches should resolve the issue.

**Pull request merged**
