### PR TITLE
NextJS moved to root

### PR DESCRIPTION
**Pull request by ElishaKay**
ready for merge: 
 - moved frontend into application folder in root
 - fixed multi_agents in NextJS frontend (it was caught at the human-in-the-loop stage) not yet supported for docker

https://github.com/user-attachments/assets/7809de76-3b7d-4f89-b94e-da01b0c83723

### CODE REVIEW

**Comment by assafelovic** [comment]
Awesome @ElishaKay there is still something weird with the video demo. Try with this chrome extension: https://www.screencastify.com/

**Comment by ElishaKay** [comment]
> Awesome @ElishaKay there is still something weird with the video demo. Try with this chrome extension: https://www.screencastify.com/

@assafelovic tried it & had the same issue with the wavy background - must be on the OS Level - passing the baton to you if you'd like to try to record on another machine

**Comment by assafelovic** [comment]
@ElishaKay this branch has conflicts can you resolve them?

**Comment by ElishaKay** [comment]
[new PR here for this ticket](https://github.com/assafelovic/gpt-researcher/pull/800)

**Pull request closed without merging**
