### PR TITLE
Specify embedding provider and model

### PR DESCRIPTION
**Pull request by kesamet**
- Allows user to specify embedding provider and model in the form `EMBEDDING="<embedding_provider>:<embedding_model>"`. Default is set `EMBEDDING="openai:text-embedding-3-large"`. This is similar to `FAST_LLM` and `SMART_LLM`
- Make deprecation warnings more intuitive
- Allows user to specify additional kwargs such as `llm_kwargs` and `embedding_kwargs` in an user-specified json file in `config_path`
- Clean up `gpt_researcher/config/config.py`. Eg `self.load_config_file` is removed as it is no longer in use

### CODE REVIEW

**Comment by kesamet** [comment]
@assafelovic This PR is to standardize variable `EMBEDDING` to be similar to that of `FAST_LLM` and `SMART_LLM` as done in #813

**Comment by danieldekay** [comment]
I have tested this with Azure, and it works!

```
FAST_LLM="azure_openai:gpt-4o-mini"
SMART_LLM="azure_openai:gpt-4o"
EMBEDDING="azure_openai:text-embedding-3-large"

```

**Comment by assafelovic** [comment]
You rock @danieldekay thank you!

**Comment by assafelovic** [comment]
@kesamet is this ready for merge?

**Comment by kesamet** [comment]
@assafelovic yes. glad that it works for Azure

**Review by assafelovic — APPROVED** [review]
This is super helpful thank you very much @kesamet !

**Comment by robertobalestri** [comment]
Currently experiencing authentication failures when attempting to fetch from Azure LLM. The API calls are returning 401 (Unauthorized) errors, despite using valid credentials that work successfully in other applications.
Details:

Error: 401 Unauthorized
Credentials are confirmed working (verified with separate working implementation)
Suspect the API call construction may need review

Request: Could someone please review the API call implementation? I can provide the current implementation details if needed.
For reference, these same Azure credentials are working correctly in my other application, suggesting the issue lies in how we're constructing the API request rather than with the credentials themselves.

**Pull request merged**
